# Generated by Django 4.1.4 on 2022-12-16 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Korisnik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64, null=True, verbose_name='Ime')),
                ('last_name', models.CharField(max_length=64, null=True, verbose_name='Prezime')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Datum rođenja')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefon')),
            ],
        ),
    ]
