# Generated by Django 4.1.4 on 2022-12-16 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hrana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=20, null=True, verbose_name='Naziv hrane')),
                ('gram_fat', models.CharField(max_length=3, null=True, verbose_name='Grama masnoce')),
                ('gram_carbs', models.CharField(max_length=3, null=True, verbose_name='Grama ugljikohidrata')),
            ],
        ),
    ]
