# Generated by Django 4.1.4 on 2022-12-16 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_desert'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidencija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=20, null=True, verbose_name='Dan')),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
