# Generated by Django 4.1.4 on 2022-12-16 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_evidencija'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrana',
            name='gram_protein',
            field=models.CharField(max_length=3, null=True, verbose_name='Grama proteina'),
        ),
    ]
