# Generated by Django 4.1.4 on 2022-12-16 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_evidencija_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidencija',
            name='meal',
            field=models.ManyToManyField(to='main.hrana'),
        ),
    ]
