# Generated by Django 4.0.5 on 2022-12-17 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_meal_evidencija_meals'),
    ]

    operations = [
        migrations.AddField(
            model_name='korisnik',
            name='fav_desert',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.desert'),
        ),
    ]
