# Generated by Django 4.0.5 on 2022-12-17 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_korisnik_fav_desert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='korisnik',
            name='fav_desert',
            field=models.OneToOneField(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.desert'),
        ),
    ]
