# Generated by Django 4.0.5 on 2022-12-17 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_korisnik_fav_desert'),
    ]

    operations = [
        migrations.RenameField(
            model_name='korisnik',
            old_name='fav_desert',
            new_name='desert_name',
        ),
    ]
