# Generated by Django 4.0.5 on 2022-12-17 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_rename_fav_desert_korisnik_desert_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='korisnik',
            name='desert_name',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.desert'),
        ),
    ]
